language: python

#addons:
#  apt:
#    packages:
#      - texlive-latex-recommended
#      - texlive-latex-extra
#      - texlive-fonts-recommended

#before_install:
#  - mkdir -p $HOME/texlive && curl -L https://github.com/urdh/texlive-blob/releases/download/20160208/texlive.tar.xz | tar -JxC $HOME/texlive

install:
# Sphinx requirements
  - pip install -r requirements.txt
# Latex requirements
#  - PATH=$HOME/texlive/bin/x86_64-linux:$PATH
#  - tlmgr option repository ftp://tug.org/historic/systems/texlive/2015/tlnet-final
#  - tlmgr update --self
#  - tlmgr install combelow
#  - tlmgr install babel-french
#  - tlmgr install babel-german
#  - tlmgr install babel-romanian
#  - tlmgr install babel-italian

before_script:
  - ./scripts/ci/transifex_push.sh

script:
  - ./scripts/build-docs.sh

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
